export default function Home(){return <main>
  <a className="skip-link" href="#content">跳到主要内容</a>
  <nav className="nav" aria-label="主导航"><a className="brand" href="#top"><span className="brand-mark">D</span><span>D.R.E.A.M. Track</span></a><div className="nav-links"><a href="#labs">Labs</a><a href="#method">方法</a><a href="#together">共创</a></div><span className="nav-note">MINGJIAN ZHANG · 2026</span></nav>
  <section className="home-hero" id="top"><div className="home-grid" aria-hidden="true"/><div className="home-copy"><p className="eyebrow"><span/> DESIGN · RESEARCH · ENGINEERING · ART · MAKING</p><h1>把想象，<br/><em>做成可以经历的未来。</em></h1><p className="hero-lead">D.R.E.A.M. Track 将实体造物与交互体验放在同一套创新系统中。学生不只学习工具，而是从一个关于未来的问题出发，跨越材料、身体、空间与数字世界。</p></div><div className="axis" aria-hidden="true"><span>ATOMS</span><i/><b>DREAM</b><i/><span>BITS</span></div></section>
  <div id="content"><section className="lab-split" id="labs"><a className="lab-card mtl-card" href="/mtl/"><span className="lab-code">MTL · TANGIBLE</span><h2>让未来，<br/>可以被触碰。</h2><p>实体系统 · 机器人 · 可穿戴 · 日常机械</p><b>进入 MTL ↗</b></a><a className="lab-card mil-card" href="/mil/"><span className="lab-code">MIL · INTERACTION</span><h2>让未来，<br/>可以被进入。</h2><p>空间交互 · 身体 · 虚拟身份 · 社会性游戏</p><b>进入 MIL ↗</b></a></section>
  <section className="system-section" id="method"><div className="section-tag"><span>02</span> ONE SYSTEM</div><div className="system-copy"><h2>两个实验室，<br/>围绕同一个未来问题工作。</h2><p>MTL 让概念获得结构、材料、传感与运动；MIL 让系统获得行为、空间、身份与体验。项目不在两个 Lab 之间传递，而是在共同的问题里同时生长。</p></div><div className="system-map"><article><span>MTL</span><h3>PHYSICAL<br/>FORM</h3><p>结构 · 材料 · 传感 · 执行</p></article><i>×</i><article><span>MIL</span><h3>HUMAN<br/>EXPERIENCE</h3><p>行为 · 空间 · 身份 · 关系</p></article><b>共同形成<br/>可运行、可体验、可讨论的系统</b></div></section>
  <section className="track-section"><div className="section-tag light"><span>03</span> HOW WE WORK</div><header><h2>从问题出发，<br/>用原型继续提问。</h2><p>DREAM Track 不把工具熟练度当作终点。学生在真实项目里经历观察、想象、制作、体验与反思。</p></header><div className="track-steps"><article><span>01</span><h3>Observe</h3><p>观察人、环境与尚未被满足的体验。</p></article><article><span>02</span><h3>Imagine</h3><p>提出不被今天工具限制的未来愿景。</p></article><article><span>03</span><h3>Prototype</h3><p>让想法成为能够运行与被体验的原型。</p></article><article><span>04</span><h3>Learn</h3><p>从人的回应、故障和意外中继续迭代。</p></article></div></section>
  <section className="home-together" id="together"><div className="section-tag"><span>04</span> CO-CREATE</div><div><p>WHAT FUTURE DO YOU WANT TO MAKE REAL?</p><h2>未来不只等待被预测，<br/>也等待被共同制作。</h2><a href="mailto:dreamtrack@moonshotacademy.cn">带着一个问题加入 DREAM Track ↗</a></div></section></div>
  <footer className="site-footer"><span>D.R.E.A.M. Track</span><span>Moonshot Academy · Mingjian Zhang</span><a href="#top">回到顶部 ↑</a></footer>
</main>}
